name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: build artifacts
        run: make release-linux && make release-mac-intel && make release-mac-applesilicon
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/tfpvc.linux-amd64.tar.gz
            bin/tfpvc.osx-amd64.tar.gz
            bin/tfpvc.linux-arm64.tar.gz
